name: Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  release-executables:
    name: Publish executable
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [win-x64, linux-x64]
        tfm: [net9.0, net10.0]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x

      - name: Determine version
        id: minver
        run: |
          dotnet tool install --global minver-cli --version 7.0.0
          VERSION=$(minver --tag-prefix v --default-pre-release-identifiers preview --auto-increment minor)

          if [ -z "$VERSION" ]; then
            echo "MinVer did not return a version."
            exit 1
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish
        run: >
          dotnet publish ./src/ResXporter/ResXporter.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --framework ${{ matrix.tfm }}
          --output ./outputs/publish/${{ matrix.tfm }}-${{ matrix.runtime }}
          --property:DebugType=None
          --property:DebugSymbols=False
          --property:PublishSingleFile=True
          --property:SelfContained=True
          --property:AssemblyName=resxporter

      - name: Archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          directory: ./outputs/publish/${{ matrix.tfm }}-${{ matrix.runtime }}
          filename: ../../resxporter-${{ matrix.tfm }}-${{ matrix.runtime }}-${{ steps.minver.outputs.version }}.zip

      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./outputs/resxporter-${{ matrix.tfm }}-${{ matrix.runtime }}-${{ steps.minver.outputs.version }}.zip

  release-tool:
    name: Publish as .NET tool
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
            10.0.x
          source-url: https://nuget.pkg.github.com/Kralizek/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: dotnet restore

      - name: Pack
        run: >
          dotnet pack ./src/ResXporter/ResXporter.csproj
          --configuration Release
          --output ./outputs/packages
          --property:AssemblyName=resxporter

      - name: List packages
        run: ls -la ./outputs/packages

      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./outputs/packages/*.nupkg

      - name: Login to NuGet.org
        id: nuget_login
        uses: NuGet/login@v1
        with:
          user: Kralizek

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./outputs/packages/*.nupkg \
            --api-key "${{ steps.nuget_login.outputs.NUGET_API_KEY }}" \
            --source https://www.nuget.org/api/v2/package \
            --skip-duplicate

      - name: Push to GitHub Package Registry
        run: |
          dotnet nuget push ./outputs/packages/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "${{ github.token }}" \
            --skip-duplicate
